import { useEffect } from "react";
import BottomNavigation from "../../common/components/BottomNavigation";
import images from "../../constants/image.constant";
import PrescAddHeader from "./components/presc.add.header";
import PrescAdd from "./components/presc.add"


export default function PrescAddPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
  });

    // 약 목록 더미 데이터
    const pillData = [
      {
        "header": {
          "resultCode": "00",
          "resultMsg": "NORMAL SERVICE."
        },
        "body": {
          "pageNo": 1,
          "totalCount": 25215,
          "numOfRows": 30,
          "items": [
            {
              "ITEM_SEQ": "200808876",
              "ITEM_NAME": "가스디알정50밀리그램(디메크로틴산마그네슘)",
              "ENTP_SEQ": "19540006",
              "ENTP_NAME": "일동제약(주)",
              "CHART": "녹색의 원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426403087300104",
              "PRINT_FRONT": "IDG",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "연두",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "7.6",
              "LENG_SHORT": "7.6",
              "THICK": "3.6",
              "IMG_REGIST_TS": "20100326",
              "CLASS_NO": "02390",
              "CLASS_NAME": "기타의 소화기관용약",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080820",
              "FORM_CODE_NAME": "당의정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20130129",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "6828500435"
            },
            {
              "ITEM_SEQ": "200808877",
              "ITEM_NAME": "페라트라정2.5밀리그램(레트로졸)",
              "ENTP_SEQ": "19560004",
              "ENTP_NAME": "(주)유한양행",
              "CHART": "어두운 황색의 원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426403087300107",
              "PRINT_FRONT": "YH",
              "PRINT_BACK": "LT",
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "노랑",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "6.1",
              "LENG_SHORT": "6.1",
              "THICK": "3.5",
              "IMG_REGIST_TS": "20100429",
              "CLASS_NO": "04210",
              "CLASS_NAME": "항악성종양제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080820",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20140130",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "1188100601"
            },
            {
              "ITEM_SEQ": "200808948",
              "ITEM_NAME": "졸뎀속붕정(졸피뎀타르타르산염)",
              "ENTP_SEQ": "20080422",
              "ENTP_NAME": "보령제약(주)",
              "CHART": "흰색의 원형 구강붕해정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426403087300128",
              "PRINT_FRONT": null,
              "PRINT_BACK": null,
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "9",
              "LENG_SHORT": "9",
              "THICK": "4",
              "IMG_REGIST_TS": "20100701",
              "CLASS_NO": "01120",
              "CLASS_NAME": "최면진정제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080825",
              "FORM_CODE_NAME": "정제",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20170901",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "1348502031"
            },
            {
              "ITEM_SEQ": "200809076",
              "ITEM_NAME": "가스프렌정(모사프리드시트르산염이수화물)",
              "ENTP_SEQ": "19760002",
              "ENTP_NAME": "경동제약(주)",
              "CHART": "분할선을 가진 흰색의 장방형 필름코팅정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426403087300143",
              "PRINT_FRONT": "KD",
              "PRINT_BACK": "분할선",
              "DRUG_SHAPE": "장방형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": "-",
              "LENG_LONG": "9.1",
              "LENG_SHORT": "4.5",
              "THICK": "3.4",
              "IMG_REGIST_TS": "20100914",
              "CLASS_NO": "02390",
              "CLASS_NAME": "기타의 소화기관용약",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080828",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Gaspren Tab",
              "CHANGE_DATE": "20211223",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "648102540",
              "BIZRNO": "1248135518"
            },
            {
              "ITEM_SEQ": "200809361",
              "ITEM_NAME": "바르탄정(발사르탄)",
              "ENTP_SEQ": "19870002",
              "ENTP_NAME": "(주)휴온스",
              "CHART": "엷은 적색의 원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426403087300155",
              "PRINT_FRONT": "V분할선T",
              "PRINT_BACK": "HS8",
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "분홍",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "6.5",
              "LENG_SHORT": "6.5",
              "THICK": "1.8",
              "IMG_REGIST_TS": "20120724",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080908",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20130129",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "8638700270"
            },
            {
              "ITEM_SEQ": "200809402",
              "ITEM_NAME": "리피논정80밀리그램(아토르바스타틴칼슘삼수화물)",
              "ENTP_SEQ": "19540001",
              "ENTP_NAME": "동아에스티(주)",
              "CHART": "이 약은 흰색의 타원형 필름코팅정이다.",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426403087300161",
              "PRINT_FRONT": "LPT",
              "PRINT_BACK": "80",
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "19.55",
              "LENG_SHORT": "10.50",
              "THICK": "7.06",
              "IMG_REGIST_TS": "20160824",
              "CLASS_NO": "02180",
              "CLASS_NAME": "동맥경화용제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080910",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Lipinon tablet 80mg (Atorvastatin calcium trihydrate)",
              "CHANGE_DATE": "20240313",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "642506260",
              "BIZRNO": "2048640122"
            },
            {
              "ITEM_SEQ": "200809710",
              "ITEM_NAME": "사르발탄정160밀리그램(발사르탄)",
              "ENTP_SEQ": "19680007",
              "ENTP_NAME": "(주)서울제약",
              "CHART": "회색빛을 띠는 오렌지색의 타원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/153432591328100009",
              "PRINT_FRONT": "SPC",
              "PRINT_BACK": "V분할선16",
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "주황",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": "-",
              "LENG_LONG": "14.19",
              "LENG_SHORT": "6.13",
              "THICK": "5.20",
              "IMG_REGIST_TS": "20110701",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080919",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Sarvaltan Tab. 160mg",
              "CHANGE_DATE": "20230502",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "652902340",
              "BIZRNO": "1338130405"
            },
            {
              "ITEM_SEQ": "200809882",
              "ITEM_NAME": "가스베트정5밀리그램(모사프리드시트르산염수화물)",
              "ENTP_SEQ": "19540006",
              "ENTP_NAME": "일동제약(주)",
              "CHART": "흰색의 장방형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/154333330132500103",
              "PRINT_FRONT": "ID·5",
              "PRINT_BACK": "분할선",
              "DRUG_SHAPE": "장방형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": "-",
              "LENG_LONG": "9",
              "LENG_SHORT": "4.6",
              "THICK": "3.2",
              "IMG_REGIST_TS": "20101223",
              "CLASS_NO": "02390",
              "CLASS_NAME": "기타의 소화기관용약",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080926",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Gasbet Tab. 5mg(Mosapride citrate hydrate)",
              "CHANGE_DATE": "20150501",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "6828500435"
            },
            {
              "ITEM_SEQ": "200809883",
              "ITEM_NAME": "아푸르탄정150밀리그램(이르베사르탄)",
              "ENTP_SEQ": "19540001",
              "ENTP_NAME": "동아에스티(주)",
              "CHART": "흰색 또는 거의 흰색의 양쪽이 볼록한 타원형 필름코팅정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426403087300198",
              "PRINT_FRONT": "AT",
              "PRINT_BACK": "150",
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "12.4",
              "LENG_SHORT": "6.4",
              "THICK": "4.95",
              "IMG_REGIST_TS": "20110627",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080926",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20200324",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "2048640122"
            },
            {
              "ITEM_SEQ": "200809909",
              "ITEM_NAME": "발사르텔정80밀리그램(발사르탄)",
              "ENTP_SEQ": "20020017",
              "ENTP_NAME": "주식회사제뉴원사이언스",
              "CHART": "분홍색의 원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/1OCNrLiTjPI",
              "PRINT_FRONT": "V분할선8",
              "PRINT_BACK": "KK",
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "분홍",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "8.2",
              "LENG_SHORT": "8.2",
              "THICK": "3.6",
              "IMG_REGIST_TS": "20120213",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080929",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Valsartel Tab. 80mg",
              "CHANGE_DATE": "20210603",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "671702870",
              "BIZRNO": "6218542600"
            },
            {
              "ITEM_SEQ": "200809910",
              "ITEM_NAME": "발사르텔정160밀리그램(발사르탄)",
              "ENTP_SEQ": "20020017",
              "ENTP_NAME": "주식회사제뉴원사이언스",
              "CHART": "회색빛을 띠는 오렌지색의 타원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/1NXa2J_Kd2y",
              "PRINT_FRONT": "V분할선16",
              "PRINT_BACK": "KK",
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "주황",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "14",
              "LENG_SHORT": "5.5",
              "THICK": "4",
              "IMG_REGIST_TS": "20120213",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080929",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Valsartel Tab. 160mg",
              "CHANGE_DATE": "20201215",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "671702810",
              "BIZRNO": "6218542600"
            },
            {
              "ITEM_SEQ": "200809959",
              "ITEM_NAME": "동광모니플루메이트정350mg",
              "ENTP_SEQ": "19560001",
              "ENTP_NAME": "동광제약(주)",
              "CHART": "크림색의 장방형 정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/152648520364900061",
              "PRINT_FRONT": "DPC",
              "PRINT_BACK": "MNF",
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "14.5",
              "LENG_SHORT": "5.5",
              "THICK": "3",
              "IMG_REGIST_TS": "20121213",
              "CLASS_NO": "01140",
              "CLASS_NAME": "해열.진통.소염제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20080929",
              "FORM_CODE_NAME": "나정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Dongkwang Morniflumate Tab.350mg",
              "CHANGE_DATE": "20211028",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "2018644250"
            },
            {
              "ITEM_SEQ": "200810125",
              "ITEM_NAME": "에스시탈정5밀리그램(에스시탈로프람옥살산염)",
              "ENTP_SEQ": "19650001",
              "ENTP_NAME": "(주)종근당",
              "CHART": "흰색의 원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426407360700016",
              "PRINT_FRONT": "CKD",
              "PRINT_BACK": "ES5",
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "6.13",
              "LENG_SHORT": "6.13",
              "THICK": "2.63",
              "IMG_REGIST_TS": "20100128",
              "CLASS_NO": "01170",
              "CLASS_NAME": "정신신경용제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081002",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Escital Tab. 5mg",
              "CHANGE_DATE": "20240213",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "643305000",
              "BIZRNO": "3128560679"
            },
            {
              "ITEM_SEQ": "200810314",
              "ITEM_NAME": "발산정80밀리그램(발사르탄)",
              "ENTP_SEQ": "19900019",
              "ENTP_NAME": "유니메드제약(주)",
              "CHART": "엷은 적색의 원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/154298763309300033",
              "PRINT_FRONT": "V분할선A",
              "PRINT_BACK": "UM",
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "분홍",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "8",
              "LENG_SHORT": "8",
              "THICK": "2",
              "IMG_REGIST_TS": "20111102",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081010",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Valsan Tab. 80mg",
              "CHANGE_DATE": "20190926",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "649505260",
              "BIZRNO": "3128109048"
            },
            {
              "ITEM_SEQ": "200810338",
              "ITEM_NAME": "가스리드정5mg(모사프리드시트르산염수화물)",
              "ENTP_SEQ": "19560004",
              "ENTP_NAME": "(주)유한양행",
              "CHART": "분할선을 가진 흰색의 장방형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426407360700025",
              "PRINT_FRONT": "YH",
              "PRINT_BACK": "G분할선5",
              "DRUG_SHAPE": "장방형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": "-",
              "LENG_LONG": "9.1",
              "LENG_SHORT": "4.6",
              "THICK": "3.1",
              "IMG_REGIST_TS": "20110223",
              "CLASS_NO": "02390",
              "CLASS_NAME": "기타의 소화기관용약",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081010",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Gasrid Tablet 5mg",
              "CHANGE_DATE": "20230209",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "642103680",
              "BIZRNO": "1188100601"
            },
            {
              "ITEM_SEQ": "200810473",
              "ITEM_NAME": "엑스반정80밀리그램(발사르탄)",
              "ENTP_SEQ": "19560011",
              "ENTP_NAME": "삼진제약(주)",
              "CHART": "분홍색의 원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/148665498867700136",
              "PRINT_FRONT": "SJ",
              "PRINT_BACK": "V분할선8",
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "분홍",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": "-",
              "LENG_LONG": "8.14",
              "LENG_SHORT": "8.14",
              "THICK": "3.57",
              "IMG_REGIST_TS": "20120618",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081017",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Exvan Tab. 80mg",
              "CHANGE_DATE": "20230203",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "647802940",
              "BIZRNO": "1248531621"
            },
            {
              "ITEM_SEQ": "200810509",
              "ITEM_NAME": "뉴멘타민서방캡슐8밀리그램(갈란타민브롬화수소산염)",
              "ENTP_SEQ": "19720014",
              "ENTP_NAME": "고려제약(주)",
              "CHART": "흰색 내지 거의 흰색의 서방코팅된 펠렛이 들어있는 불투명한 상·하 흰색의 경질캡슐제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/151706776344700079",
              "PRINT_FRONT": "KDC NTC     8",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "장방형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": "하양",
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "14",
              "LENG_SHORT": "4",
              "THICK": "4",
              "IMG_REGIST_TS": "20091105",
              "CLASS_NO": "01190",
              "CLASS_NAME": "기타의 중추신경용약",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081020",
              "FORM_CODE_NAME": "스팬슐",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Newmentamine EX Cap. 8mg",
              "CHANGE_DATE": "20230628",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "642802140",
              "BIZRNO": "1268104796"
            },
            {
              "ITEM_SEQ": "200810522",
              "ITEM_NAME": "발트렙정160밀리그램(발사르탄)",
              "ENTP_SEQ": "19760002",
              "ENTP_NAME": "경동제약(주)",
              "CHART": "회색빛을 띠는 오렌지색의 타원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426407360700046",
              "PRINT_FRONT": "KD분할선VT",
              "PRINT_BACK": "160",
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "주황",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "15.00",
              "LENG_SHORT": "6.35",
              "THICK": "4.35",
              "IMG_REGIST_TS": "20110316",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081020",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "valtrep tab. 160mg",
              "CHANGE_DATE": "20200401",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "648102940",
              "BIZRNO": "1248135518"
            },
            {
              "ITEM_SEQ": "200810789",
              "ITEM_NAME": "수로신디정(탐스로신염산염)",
              "ENTP_SEQ": "19570001",
              "ENTP_NAME": "(주)에스트라",
              "CHART": "흰색의 원형 정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426407360700049",
              "PRINT_FRONT": "PAC",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "9.0",
              "LENG_SHORT": "9.0",
              "THICK": "3.5",
              "IMG_REGIST_TS": "20100219",
              "CLASS_NO": "02590",
              "CLASS_NAME": "기타의 비뇨생식기관 및 항문용약",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081103",
              "FORM_CODE_NAME": null,
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20140130",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "1068138502"
            },
            {
              "ITEM_SEQ": "200810870",
              "ITEM_NAME": "로수로드정10밀리그램(로수바스타틴칼슘)",
              "ENTP_SEQ": "19650001",
              "ENTP_NAME": "(주)종근당",
              "CHART": "분홍색의 원형 필름코팅정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/151706768099900035",
              "PRINT_FRONT": "CKDRSD10",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "분홍",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "7",
              "LENG_SHORT": "7",
              "THICK": "3",
              "IMG_REGIST_TS": "20090724",
              "CLASS_NO": "02180",
              "CLASS_NAME": "동맥경화용제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081107",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Rosulord Tab. 10mg",
              "CHANGE_DATE": "20240412",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "643305080",
              "BIZRNO": "3128560679"
            },
            {
              "ITEM_SEQ": "200811004",
              "ITEM_NAME": "슈니펜정(모니플루메이트)",
              "ENTP_SEQ": "19580004",
              "ENTP_NAME": "안국약품(주)",
              "CHART": "크림색의 장방형 정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426407360700065",
              "PRINT_FRONT": "AG",
              "PRINT_BACK": "MNF",
              "DRUG_SHAPE": "장방형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "14.2",
              "LENG_SHORT": "7.2",
              "THICK": "5.2",
              "IMG_REGIST_TS": "20100823",
              "CLASS_NO": "01140",
              "CLASS_NAME": "해열.진통.소염제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081114",
              "FORM_CODE_NAME": "나정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "SCHUNIFEN Tab.",
              "CHANGE_DATE": "20191030",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "650203480",
              "BIZRNO": "1188104188"
            },
            {
              "ITEM_SEQ": "200811104",
              "ITEM_NAME": "디오살탄정160밀리그램(발사르탄)",
              "ENTP_SEQ": "19560004",
              "ENTP_NAME": "(주)유한양행",
              "CHART": "회색빛을 띠는 오렌지색의 타원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/154298782012500025",
              "PRINT_FRONT": "Y분할선H",
              "PRINT_BACK": "160",
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "노랑",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "14.4",
              "LENG_SHORT": "5.6",
              "THICK": "5.0",
              "IMG_REGIST_TS": "20111024",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081120",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Diosartan Tablet 160mg",
              "CHANGE_DATE": "20191129",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "642104020",
              "BIZRNO": "1188100601"
            },
            {
              "ITEM_SEQ": "200811105",
              "ITEM_NAME": "디오살탄정80밀리그램(발사르탄)",
              "ENTP_SEQ": "19560004",
              "ENTP_NAME": "(주)유한양행",
              "CHART": "엷은 적색의 원형필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/154298782012500031",
              "PRINT_FRONT": "Y분할선H",
              "PRINT_BACK": "80",
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "분홍",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "8.1",
              "LENG_SHORT": "8.1",
              "THICK": "3.4",
              "IMG_REGIST_TS": "20111024",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081120",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Diosartan Tablet 80mg",
              "CHANGE_DATE": "20191129",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "642104030",
              "BIZRNO": "1188100601"
            },
            {
              "ITEM_SEQ": "200811403",
              "ITEM_NAME": "칸데사르정8밀리그램(칸데사르탄실렉세틸)",
              "ENTP_SEQ": "19590003",
              "ENTP_NAME": "(주)한독",
              "CHART": "양면이 볼록한 원형의 밝은 분홍색 정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/151706776344800062",
              "PRINT_FRONT": "마크분할선C8",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "분홍",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "7.0",
              "LENG_SHORT": "7.0",
              "THICK": "3.2",
              "IMG_REGIST_TS": "20091006",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081204",
              "FORM_CODE_NAME": "나정",
              "MARK_CODE_FRONT_ANAL": "P,d",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147938640332900187",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "CANDESAR TAB.8mg",
              "CHANGE_DATE": "20130129",
              "MARK_CODE_FRONT": "r0062",
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "2208100530"
            },
            {
              "ITEM_SEQ": "200811404",
              "ITEM_NAME": "칸데사르정16밀리그램(칸데사르탄실렉세틸)",
              "ENTP_SEQ": "19570001",
              "ENTP_NAME": "(주)에스트라",
              "CHART": "양면이 볼록한 원형의 분홍색 정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/151706776344800068",
              "PRINT_FRONT": "마크분할선C16",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "분홍",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "7.0",
              "LENG_SHORT": "7.0",
              "THICK": "3.2",
              "IMG_REGIST_TS": "20091006",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081204",
              "FORM_CODE_NAME": "나정",
              "MARK_CODE_FRONT_ANAL": "P,d",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147938640332900187",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20130129",
              "MARK_CODE_FRONT": "r0062",
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "1068138502"
            },
            {
              "ITEM_SEQ": "200811619",
              "ITEM_NAME": "디로탄정160mg(발사르탄)",
              "ENTP_SEQ": "19550001",
              "ENTP_NAME": "이연제약(주)",
              "CHART": "회색빛을 띠는 오렌지색의 타원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426407360700097",
              "PRINT_FRONT": "R분할선Y",
              "PRINT_BACK": "160",
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "주황",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "14",
              "LENG_SHORT": "5",
              "THICK": "3",
              "IMG_REGIST_TS": "20120313",
              "CLASS_NO": "02140",
              "CLASS_NAME": "혈압강하제",
              "ETC_OTC_NAME": "전문의약품",
              "ITEM_PERMIT_DATE": "20081216",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Dirotan Tab. 160mg",
              "CHANGE_DATE": "20220811",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": "658602540",
              "BIZRNO": "3018505394"
            },
            {
              "ITEM_SEQ": "200811883",
              "ITEM_NAME": "인케어정(옥수수불검화정량추출물)",
              "ENTP_SEQ": "19600009",
              "ENTP_NAME": "(주)한국비엠아이",
              "CHART": "주황색의 원형 필름코팅정",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426407360700117",
              "PRINT_FRONT": "BMI",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "원형",
              "COLOR_CLASS1": "주황",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "15",
              "LENG_SHORT": "15",
              "THICK": "3",
              "IMG_REGIST_TS": "20130128",
              "CLASS_NO": "02310",
              "CLASS_NAME": "치과구강용약",
              "ETC_OTC_NAME": "일반의약품",
              "ITEM_PERMIT_DATE": "20081226",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20130103",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "1248636434"
            },
            {
              "ITEM_SEQ": "200811971",
              "ITEM_NAME": "제이코정",
              "ENTP_SEQ": "20100618",
              "ENTP_NAME": "제이에스제약(주)",
              "CHART": "흰색의 장방형 필름코팅정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/150834126208100152",
              "PRINT_FRONT": "COΛ",
              "PRINT_BACK": "분할선",
              "DRUG_SHAPE": "장방형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": "-",
              "LENG_LONG": "15",
              "LENG_SHORT": "7.45",
              "THICK": "5.7",
              "IMG_REGIST_TS": "20100621",
              "CLASS_NO": "01140",
              "CLASS_NAME": "해열.진통.소염제",
              "ETC_OTC_NAME": "일반의약품",
              "ITEM_PERMIT_DATE": "20081230",
              "FORM_CODE_NAME": "필름코팅정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": null,
              "CHANGE_DATE": "20150130",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "4098617454"
            },
            {
              "ITEM_SEQ": "200900005",
              "ITEM_NAME": "노페인에프정(수출용)",
              "ENTP_SEQ": "20020020",
              "ENTP_NAME": "(주)휴온스생명과학",
              "CHART": "백색의 타원형 정제",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/147426407360700155",
              "PRINT_FRONT": "BT분할선NF",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "하양",
              "COLOR_CLASS2": null,
              "LINE_FRONT": "-",
              "LINE_BACK": null,
              "LENG_LONG": "19",
              "LENG_SHORT": "10",
              "THICK": "6",
              "IMG_REGIST_TS": "20110707",
              "CLASS_NO": "01140",
              "CLASS_NAME": "해열.진통.소염제",
              "ETC_OTC_NAME": "일반의약품",
              "ITEM_PERMIT_DATE": "20090102",
              "FORM_CODE_NAME": "나정",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Nopain F Tab.",
              "CHANGE_DATE": "20150131",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "8488100323"
            },
            {
              "ITEM_SEQ": "200900018",
              "ITEM_NAME": "깅코탄연질캡슐120밀리그램(은행엽건조엑스)",
              "ENTP_SEQ": "19950015",
              "ENTP_NAME": "한국프라임제약(주)",
              "CHART": "암갈색의 유상내용물이 든 녹색의 타원형 연질캡슐",
              "ITEM_IMAGE": "https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/1Mky9VD2vUV",
              "PRINT_FRONT": "깅코탄",
              "PRINT_BACK": null,
              "DRUG_SHAPE": "타원형",
              "COLOR_CLASS1": "초록",
              "COLOR_CLASS2": null,
              "LINE_FRONT": null,
              "LINE_BACK": null,
              "LENG_LONG": "14.7",
              "LENG_SHORT": "8.5",
              "THICK": "8.5",
              "IMG_REGIST_TS": "20100325",
              "CLASS_NO": "02190",
              "CLASS_NAME": "기타의 순환계용약",
              "ETC_OTC_NAME": "일반의약품",
              "ITEM_PERMIT_DATE": "20090102",
              "FORM_CODE_NAME": "연질캡슐제, 현탁상",
              "MARK_CODE_FRONT_ANAL": "",
              "MARK_CODE_BACK_ANAL": "",
              "MARK_CODE_FRONT_IMG": "",
              "MARK_CODE_BACK_IMG": "",
              "ITEM_ENG_NAME": "Gingcotan Soft Cap. 120mg",
              "CHANGE_DATE": "20211025",
              "MARK_CODE_FRONT": null,
              "MARK_CODE_BACK": null,
              "EDI_CODE": null,
              "BIZRNO": "4028524506"
            }
          ]
        }
      }
    ]

  return (
    <div className="relative">
      <PrescAddHeader title="처방 목록 추가" />
      <div className="flex justify-center items-center">
        <div className="bg-opacity-100 w-[85%] min-h-screen">
          <PrescAdd pill={pillData}/>
        </div>
      </div>

      <BottomNavigation active="2" />
      {/* 배경 */}
      <div className="absolute bottom-0 w-full">
        <div className="relative w-full h-auto bottom-0">
          <img
            src={images.wave}
            alt="Background"
            className="fixed bottom-0 w-full h-60 z-[-1]"
          />
        </div>
      </div>
    </div>
  );
}
